default:
  tags:
    - docker-linux

stages:
  - test
  - deploy

include:
- local: '/.gitlab/test-system.yml'
#- local: '/.gitlab/deploy-pages.yml'
- local: '/.gitlab/deploy-docker.yml'
- template: Jobs/SAST.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml
# - local: '/.gitlab/mirror-main.yml' # Push mirror is disabled.

sast:
  stage: test
